# Generated by Django 3.2.9 on 2021-12-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_number', models.IntegerField(default=1, verbose_name='Количество заказов')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Зарплата')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField(auto_now_add=True, verbose_name='Дата получения заказа')),
                ('deadline', models.DateField(null=True, verbose_name='Крайний срок')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='PersonalityFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Личное дело',
                'verbose_name_plural': 'Личные дела',
                'db_table': 'personality_files',
            },
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Программист',
                'verbose_name_plural': 'Программисты',
                'db_table': 'programmers',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language_name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'db_table': 'programming_languages',
            },
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.employee', verbose_name='Сотрудник')),
                ('programming_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_software_development.programminglanguage', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Тестировщик',
                'verbose_name_plural': 'Тестировщики',
                'db_table': 'testers',
            },
        ),
        migrations.CreateModel(
            name='Teamlead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Тимлид',
                'verbose_name_plural': 'Тимлиды',
                'db_table': 'teamleads',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateField(auto_now_add=True, verbose_name='Дата начала')),
                ('ending_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.order', verbose_name='Заказ')),
                ('programmers', models.ManyToManyField(db_table='programmers_in_projects', to='app_software_development.Programmer', verbose_name='Программисты')),
                ('programming_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_software_development.programminglanguage', verbose_name='Язык программирования')),
                ('teamlead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_software_development.teamlead', verbose_name='Тимлид')),
                ('testers', models.ManyToManyField(db_table='testers_in_projects', to='app_software_development.Tester', verbose_name='Тестировщики')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='programmer',
            name='programming_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_software_development.programminglanguage', verbose_name='Язык программирования'),
        ),
        migrations.AddField(
            model_name='order',
            name='required_programming_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_software_development.programminglanguage', verbose_name='Требуемый язык программирования'),
        ),
        migrations.AddField(
            model_name='employee',
            name='personality_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.personalityfile', verbose_name='Личное дело'),
        ),
        migrations.AddField(
            model_name='client',
            name='personality_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_software_development.personalityfile', verbose_name='Личное дело'),
        ),
    ]
