# Generated by Django 3.2.9 on 2021-12-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software_development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beginning_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
