# Generated by Django 3.2.9 on 2021-12-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_software_development', '0003_alter_client_orders_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='beginning_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
    ]
